# Generated by Django 4.2.19 on 2025-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_userprofile_linkedin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingschedule',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Custom title template for posts', max_length=300),
        ),
    ]
