# Generated by Django 4.2.20 on 2025-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapingschedule_custom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meta_token',
            field=models.TextField(blank=True, help_text='Meta token for Facebook/Threads'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meta_user_id',
            field=models.CharField(blank=True, help_text='Meta User ID/Page ID for posting', max_length=100),
        ),
    ]
