# Generated by Django 4.2.20 on 2025-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_userprofile_meta_token_userprofile_meta_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontent',
            name='posted_to_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='telegram_post_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Telegram bot token for sending messages', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Comma-separated list of chat IDs', max_length=255),
        ),
    ]
